const fs=require('fs');
const path=require('path');
const {downloadMediaMessage}=require('@whiskeysockets/baileys');
const DATA_DIR=path.join(__dirname,'data');
const SETTINGS_FILE=path.join(DATA_DIR,'antidel-settings.json');
const MEDIA_DIR=path.join(DATA_DIR,'antidel-media');
if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
if(!fs.existsSync(MEDIA_DIR))fs.mkdirSync(MEDIA_DIR,{recursive:true});
if(!global.antiDelStore)global.antiDelStore=new Map();
function settings(){try{return fs.existsSync(SETTINGS_FILE)?JSON.parse(fs.readFileSync(SETTINGS_FILE,'utf8')):{}}catch(e){console.error('❌ AntiDel settings:',e.message);return{}}}
function save(s){try{fs.writeFileSync(SETTINGS_FILE,JSON.stringify(s,null,2))}catch(e){console.error('❌ AntiDel save:',e.message)}}
function setAntiDel(chat,on){if(!chat)return;const s=settings();s[chat]=!!on;save(s);console.log(`🛡️ Anti-delete ${s[chat]?'ON':'OFF'} -> ${chat}`)}
function isAntiDel(chat){return !!settings()[chat]}
function unwrap(m){if(!m)return null;if(m.ephemeralMessage?.message)return unwrap(m.ephemeralMessage.message);if(m.viewOnceMessage?.message)return unwrap(m.viewOnceMessage.message);if(m.viewOnceMessageV2?.message)return unwrap(m.viewOnceMessageV2.message);if(m.viewOnceMessageV2Extension?.message)return unwrap(m.viewOnceMessageV2Extension.message);return m}
function typeOf(m){const x=unwrap(m);if(!x)return null;for(const t of ['conversation','extendedTextMessage','imageMessage','videoMessage','audioMessage','stickerMessage','documentMessage','contactMessage','locationMessage'])if(x[t])return t;return null}
function safe(v){return String(v).replace(/[^a-zA-Z0-9._-]/g,'_')}
function ext(type,d){if(type==='imageMessage'){const m=d?.mimetype||'';return m.includes('png')?'png':m.includes('webp')?'webp':'jpg'}if(type==='videoMessage')return'mp4';if(type==='audioMessage')return'ogg';if(type==='stickerMessage')return'webp';if(type==='documentMessage'){const e=path.extname(d?.fileName||'').replace('.','');return e||'bin'}return'bin'}
async function storeMessage(sock,msg){try{if(!msg?.key||!msg.message)return;const root=unwrap(msg.message);if(root?.protocolMessage)return;const chat=msg.key.remoteJid;if(!chat||!isAntiDel(chat))return;const message=unwrap(msg.message),type=typeOf(message),id=msg.key.id;if(!type||!id||global.antiDelStore.has(id))return;const sender=msg.key.participant||chat,pushName=msg.pushName||'Unknown User';if(type==='conversation'||type==='extendedTextMessage'){const text=type==='conversation'?message.conversation||'':message.extendedTextMessage?.text||'';global.antiDelStore.set(id,{id,chatId:chat,sender,pushName,type,text,timestamp:Date.now()});console.log(`💾 Anti-Delete saved TEXT: ${id}`);return}if(!['imageMessage','videoMessage','audioMessage','stickerMessage','documentMessage'].includes(type))return;let buffer;try{buffer=await downloadMediaMessage({key:msg.key,message:msg.message},'buffer',{}, {logger:{info(){},error(){},warn(){},debug(){},trace(){},child(){return this}}})}catch(e){console.error(`❌ Failed to save ${type}:`,e.message);return}if(!buffer?.length)return;const d=message[type],folder=path.join(MEDIA_DIR,safe(chat));if(!fs.existsSync(folder))fs.mkdirSync(folder,{recursive:true});const filePath=path.join(folder,`${safe(id)}.${ext(type,d)}`);fs.writeFileSync(filePath,buffer);global.antiDelStore.set(id,{id,chatId:chat,sender,pushName,type,filePath,mimetype:d?.mimetype,fileName:d?.fileName||`recovered.${ext(type,d)}`,caption:d?.caption||'',ptt:!!d?.ptt,timestamp:Date.now()});console.log(`✅ Anti-Delete saved ${type}: ${filePath}`)}catch(e){console.error('❌ Anti-Delete store:',e.message)}}
async function recoverDeleted(sock,revoke){try{const p=revoke?.message?.protocolMessage;if(!p?.key?.id)return;const key=p.key,chat=key.remoteJid||revoke.key?.remoteJid;if(!chat||!isAntiDel(chat))return;const saved=global.antiDelStore.get(key.id);if(!saved){console.log(`⚠️ Deleted message not found: ${key.id}`);return}console.log(`♻️ Recovering deleted ${saved.type}: ${key.id}`);const tag=saved.sender?.includes('@')?`@${saved.sender.split('@')[0]}`:saved.pushName,header=`♻️ *ANTI-DELETE RECOVERED*\n\n👤 *Sender:* ${saved.pushName}\n📱 *User:* ${tag}\n\n`;if(saved.type==='conversation'||saved.type==='extendedTextMessage'){await sock.sendMessage(chat,{text:header+`💬 *Message:*\n${saved.text||''}`,mentions:saved.sender?[saved.sender]:[]});global.antiDelStore.delete(key.id);return}if(!saved.filePath||!fs.existsSync(saved.filePath)){global.antiDelStore.delete(key.id);return}const b=fs.readFileSync(saved.filePath),cap=header+(saved.caption?`\n📝 ${saved.caption}`:'');if(saved.type==='imageMessage')await sock.sendMessage(chat,{image:b,caption:cap,mentions:saved.sender?[saved.sender]:[]});else if(saved.type==='videoMessage')await sock.sendMessage(chat,{video:b,caption:cap,mentions:saved.sender?[saved.sender]:[]});else if(saved.type==='audioMessage'){await sock.sendMessage(chat,{audio:b,mimetype:saved.mimetype||'audio/ogg; codecs=opus',ptt:!!saved.ptt});await sock.sendMessage(chat,{text:header,mentions:saved.sender?[saved.sender]:[]})}else if(saved.type==='stickerMessage'){await sock.sendMessage(chat,{sticker:b});await sock.sendMessage(chat,{text:header,mentions:saved.sender?[saved.sender]:[]})}else if(saved.type==='documentMessage')await sock.sendMessage(chat,{document:b,mimetype:saved.mimetype||'application/octet-stream',fileName:saved.fileName||'recovered-file',caption:cap,mentions:saved.sender?[saved.sender]:[]});console.log(`✅ Recovered ${saved.type}`);global.antiDelStore.delete(key.id)}catch(e){console.error('❌ Anti-Delete recovery:',e.message)}}
module.exports={setAntiDel,isAntiDel,storeMessage,recoverDeleted};
